name: Version Resolver

on:
  workflow_call:
    outputs:
      version_name:
        value: ${{ jobs.version.outputs.version_name }}
      version_code:
        value: ${{ jobs.version.outputs.version_code }}
      is_ci:
        value: "true"

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.vars.outputs.version_name }}
      version_code: ${{ steps.vars.outputs.version_code }}
      is_ci: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from gradle.properties
        id: vars
        shell: bash
        run: |
          VERSION=$(grep '^versionName=' gradle.properties | cut -d'=' -f2)
          echo "version_name=$VERSION" >> $GITHUB_OUTPUT
          echo "version_code=${{ github.run_number }}" >> $GITHUB_OUTPUT
