name: Deploy to RuStore
# переменные все добавлены, надо проверить когда вручную пройдёт релиз в русторе
# обязательно проверить версию и доки для экшена ru-store/rustore-upload-action@v1.1.0
# на момент создания пайплайна этому экшену 4 дня

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'

jobs:
  common_env:
    uses: ./.github/workflows/_common_env.yml

  build:
    needs: common_env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ../release.keystore

      - name: Build Release apk
        run: ./gradlew assembleRelease
        env:
          ORG_GRADLE_PROJECT_versionName: ${{ needs.common_env.outputs.version_name }}
          ORG_GRADLE_PROJECT_versionCode: ${{ needs.common_env.outputs.version_code }}
          ORG_GRADLE_PROJECT_isCi: ${{ needs.common_env.outputs.is_ci }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          VERSION_CODE: ${{ needs.common_env.outputs.version_code }}
          VERSION_NAME: ${{ needs.common_env.outputs.version_name }}

      - name: Upload to RuStore
        uses: ru-store/rustore-upload-action@v1.1.0
        with:
          key-id: ${{ secrets.RUSTORE_KEY_ID }}
          private-key: ${{ secrets.RUSTORE_PRIVATE_KEY }}
          app-id: org.patifiner.client
          bundle-path: androidApp/build/outputs/apk/release/composeApp-release.apk
          publish-type: "MANUAL"