name: Mobile Publish

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['gradle.properties']

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Environment
        id: setup
        uses: ./.github/actions/setup-env

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > release.keystore

      - name: Build Release APK's
        run: ./gradlew assembleRelease assembleDebug
        env:
          KEYSTORE_FILE_PATH: ${{ github.workspace }}/release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_isCi: "true"
          ORG_GRADLE_PROJECT_versionName: ${{ steps.setup.outputs.version_name }}
          ORG_GRADLE_PROJECT_versionCode: ${{ steps.setup.outputs.version_code }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.setup.outputs.version_name }}
          name: Release v${{ steps.setup.outputs.version_name }}
          generate_release_notes: true
          body: |
            ### 🚀 New Build Info
            - **Version:** ${{ steps.setup.outputs.version_name }}
            - **Build Number:** ${{ steps.setup.outputs.version_code }}
          draft: false
          prerelease: false
          files: |
            androidApp/build/outputs/apk/release/*.apk
            androidApp/build/outputs/apk/debug/*.apk
